# A simple template script to run OpenMP batch jobs on ARCHER at EPCC
#
# You have to do three things to run a program with it:
#
# 1) Make a copy of the script with the same name as your OpenMP executable,
#    eg if the executable is 'myjob' then type: cp ompbatch.pbs myjob.pbs
#
# 2) Set the variable OMP_NUM_THREADS appropriately (up to a maximum of 24)
#
# 3) Submit the script: qsub myjob.pbs
#
# All screen output (stdout and stderr) will appear in a file called
# myjob.pbs.oXXXXX, where XXXXX is the job number assigned at submit time.
#
# David Henty, EPCC, 25/11/2014
#

#PBS -A y14-CDT-Soton
#PBS -j oe
#PBS -l walltime=00:01:00
#PBS -l select=1

#----------------------------------------------------------#
# You should only have to change the following single line #
#----------------------------------------------------------#

cd $PBS_O_WORKDIR

echo '--------------------------------------------------------------------------------'


echo 'Started at' `date`
echo '--------------------------------------------------------------------------------'

for threads in {1,2,3,6,12,24}; do
	export OMP_NUM_THREADS=$threads
	echo '++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++'
	echo 'Running on ' $OMP_NUM_THREADS 'threads'
	echo '++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++'
	for p in {"loopsAfsSimple","loopsAfsFast"}; do
		echo 'Running OpenMP program: ' $p
		(time aprun -n 1 -d $OMP_NUM_THREADS ./$p) 2>&1
		echo '--------------------------------------------------------------------------------'
	done
done

echo '--------------------------------------------------------------------------------'
echo 'Finished at' `date`
~
